on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    # Runs on the 39th minute of the 4 & 15th hour of each day. i.e. 4:39 and 15:39.
    # See more cron syntax documentation at https://docs.github.com/en/actions/reference/events-that-trigger-workflows#schedule
    - cron: '39 4,15 * * *'

jobs:
  ios:
    strategy:
      matrix:
        device: # Device names must be shown in `xcrun simctl list devices`
          - 'iPhone 12'  # we are not specifying the iOS version as it tends to change
      fail-fast: false
    runs-on: 'macos-11'
    steps:
      - name: 'List Simulators'
        run: 'xcrun simctl list devices'

      - name: 'Start Simulator'
        run: xcrun simctl boot "${{ matrix.device }}"

      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1

      - name: 'Run Flutter Driver tests'
        timeout-minutes: 30
        run: |
          flutter pub get
          cd test_integration && ./run_integration_tests.sh

  android:
    strategy:
      matrix:
        api-level: [21, 29]
      fail-fast: false

    # ubuntu-latest cannot be used as it is only a docker container, and unfortunately running
    # hardware acceleration in container is not allowed by android emulator.
    runs-on: 'macos-latest'

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '8.x'

      - uses: subosito/flutter-action@v1

      - name: 'Run Flutter Driver tests'
        timeout-minutes: 30
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          script: |
            /Users/runner/Library/Android/sdk/tools/bin/avdmanager list
            flutter pub get
            cd test_integration && ./run_integration_tests.sh
